---

- name: Add managed config files for supervisor programs.
  template:
    src: program.j2
    dest: "{{supervisor_include_path}}/{{item.name}}.conf"
    owner: root
    group: root
    mode: 0644
  with_items: "{{supervisor_programs}}"
  when: supervisor_programs|length > 0
  notify: restart supervisor managed programs

- name: Add managed program groups config file (if any groups are configured).
  template:
    src: groups.j2
    dest: "{{supervisor_include_path}}/groups.conf"
    owner: root
    group: root
    mode: 0644
  when: supervisor_program_groups|length > 0
  notify: restart supervisor managed programs

- name: Find conf files in supervisor_include_path
  find:
    paths: "{{supervisor_include_path}}"
    patterns: '*.conf'
    file_type: 'file'
  register: all_supervisor_confs

- name: Remove un-managed supervisor config files
  file:
    path: "{{ item.path }}"
    state: absent
  with_items: "{{all_supervisor_confs.files }}"
  # this removes the groups.yml config if supervisor_program_groups becomes empty
  when: (item.path.split('/')[-1].split('.')[0]) not in (supervisor_programs | map(attribute='name') | list) +
                    (supervisor_program_groups | length>0) | ternary(['groups'],[])
  notify: restart supervisor managed programs
