---

- name: start supervisord
  service:
    name: supervisord
    state: started

- name: restart supervisord
  service:
    name: supervisord
    state: restarted

- name: restart supervisor managed programs
  supervisorctl:
    name: "{{item.name}}"
    state: restarted
  when: item.autostart
  with_items: "{{supervisor_programs}}"

- name: stop supervisord
  service:
    name: supervisord
    state: stopped

- name: restart syslog
  service:
    name: rsyslog
    state: restarted
